### PR TITLE
Take copy of return value if explicit by value used, when mocking return for return by ref or const ref method.

### PR DESCRIPTION
**Pull request by malcolmdavey**
For issue https://github.com/eranpeer/FakeIt/issues/258

### CODE REVIEW

**Comment by malcolmdavey** [comment]
Actually the move there is optional, and just an optimisation. It's a shared_ptr so it can be copied fine.

**Comment by FranckRJ** [comment]
I think that the feature may be a bit obscure. It's not really obvious what it does, it feel a bit like a hack. Maybe having a separate function would be a better idea, what do you think ?

**Comment by malcolmdavey** [comment]
Yeah - initially I was thinking of a "ReturnCopy" function, but then found this also worked - wasn't sure if it was deliberate or an accident. Am happy to make a "ReturnCopy" and a "AlwaysReturnCopy"

**Comment by malcolmdavey** [comment]
Hi @FranckRJ . Any time to review?

**Comment by FranckRJ** [comment]
I'll try to look at it next week.

**Comment by malcolmdavey** [comment]
Hi @FranckRJ. Sorry to bother you again. Is this one reasonable to go ahead?

**Comment by malcolmdavey** [comment]
Hi @eranpeer . Are you still interested in participating in this project?

**Comment by malcolmdavey** [comment]
Hi @FranckRJ . Do you have an idea if you will be able to get to this? Or are there others who might be able to.
(FYI - I think this one is lower priority than the Verify of reference parameters issue, but hadn't started that yet..)

**Comment by FranckRJ** [comment]
Sorry for the late reply, last time I checked this PR I was a bit confused about it and didn't know what to do, because it contains multiple changes and I have a different opinion on what to do for all of them.

- Extending lambda lifetime: a needed fix, I would like to merge that in 2.3.1
- ReturnCopy: a good new feature, but as a new feature I think it should better be merged in 2.4.0
- Return(T&& t): from what I understand it's to fix an issue when passing rvalues to `Return` and the return type of the mocked function is a reference, but I have several questions about it, that makes me not too confident about merging it in its current state:
  - why using a new template parameter instead of `R` like others `Return` ? I don't think it's a bad idea per se but it's not how others `Return` a written and change a bit how the method work, I think it may be better to keep it consistent.
  - why do you check that T is copy constructible ? What about move-only types ?

**Comment by FranckRJ** [comment]
So ideally I would like that these 3 changes have their own PR, I understand that it's a bit annoying to do so I can to it myself if you want.

**Comment by malcolmdavey** [comment]
Hi @FranckRJ . Sorry, not sure what happened with the PR. It does seem to contain changes from other PR's which may have been merged already. I'll try to fix it up..

**Comment by FranckRJ** [comment]
I aim to release the 2.3.1 next week, I would like to have the extension of lambda's lifetime merged in. Do you mind if I do the PR myself if you don't have the time to do it ?

**Comment by malcolmdavey** [comment]
Yeah - that's fine. Not sure I'll have time in the next week or so.

**Comment by malcolmdavey** [comment]
No worries, I can fix it up.

**Pull request closed without merging**
