### PR TITLE
FIX(DynamicProxy): std::vector assert error in getMethodMock after Reset

### PR DESCRIPTION
**Pull request by bcachet**
Hello,

Time to time, after a Reset, I got an assertion error generated by std::vector when  trying to generate a Stub.

Diving into the code point that error comes from DynamicProxy. 
In DynamicProxy, after a Reset, _methodMocks size is not reset to the size of the VTable of the mocked Interface.
When calling getMethodMock method, we got an assertion error while trying to access not existing index.

I'm not really aware of all the build environment.
Do I need to commit and push generated headers files ? How do you proceed to generate them ?

Sincerely

Bertrand

### CODE REVIEW

**Comment by eranpeer** [comment]
Thanks,
You need to check the source out as described in the section "Using the source header files" on the main page.
Then you can change the code and submit a pull request.

**Comment by bcachet** [comment]
I modified the generate_fakeit_single_header.py script to specify that it requires python3 and in order to generate single_header subdirs only when not existing (overwise, os.makedirs crash).

**Comment by eranpeer** [comment]
Thanks,
Can you please add a unit test that reproduces the problem. A test that would fail before your fix and pass after the fix.

**Comment by bcachet** [comment]
Using operator[] on empty vector, is undefined behavior.
I do not manage to produce a test that fail every time. I got one that crash almost all the time on VS, but it worked like a charm on GCC/Clang.
I will try to provide one.

**Comment by eranpeer** [comment]
Thanks!!!

**Comment by bcachet** [comment]
I finally manage to create one.
```cpp
struct foo_bar {
virtual int foo() = 0;
virtual int bar() = 0;
}
```
Initially I always stubbed foo method, which some time break on VisualStudio but work on all compilers.
But when stubbing the second methods of the interface (bar), it breaks all the time.

**Pull request merged**
