### PR TITLE
Fix fakeit for catch 2.1.0

### PR DESCRIPTION
**Pull request by emersonmx**

### CODE REVIEW

**Comment by loudedtwist** [comment]
it does solve the problem! thank you !

**Comment by krissmi** [comment]
This seems to fix the problem.  Thanks!

**Comment by jeppefrandsen** [comment]
@eranpeer can this PR be merged? Thanks

**Comment by vvollaro** [comment]
+1 this PR is really useful

**Comment by lordjeb** [comment]
+1

**Comment by eranpeer** [comment]
Thanks, it is great help.

**Comment by eranpeer** [comment]
Thanks, it is great help.

**Pull request merged**
