### PR TITLE
Fix colliding mocking context ids

### PR DESCRIPTION
**Pull request by otrempe**
Fixes https://github.com/eranpeer/FakeIt/issues/294

### CODE REVIEW

**Comment by otrempe** [comment]
Ok... I need to rework constExprHash so no C++14 features are used

**Comment by FranckRJ** [comment]
I haven't tried to see if it give the same result, but maybe something like this ?

```cpp
constexpr size_t hash(const char* str, size_t val = 14695981039346656037ULL)
{
    return *str == '\0'
        ? val
        : hash(++str, val ^ static_cast<size_t>(*str) * 1099511628211ULL);
}
```

https://godbolt.org/z/7vqYqPTPh

**Comment by FranckRJ** [comment]
You need to add the new test files to https://github.com/eranpeer/FakeIt/blob/master/build/sources.mk, otherwise they won't be run for GCC / Clang.

**Comment by otrempe** [comment]
Coverage decreased by 4.0e-05% :open_mouth: :laughing:

The Visual Studio build yields lots of `warning C4307: '*': integral constant overflow`
However, Microsoft stopped issuing this warning starting with MSVC v19.23.

**Comment by otrempe** [comment]
I guess my .h/.cpp helper files need to be added to the sources.mk as well

**Comment by FranckRJ** [comment]
You're right, but only the .cpp.

**Comment by FranckRJ** [comment]
Thanks for the fix, I'll try to look more into it next week, I'll do some benchmark because I'm curious if it affect compilation time or not.

**Comment by FranckRJ** [comment]
I didn't see any measurable difference in compilation time with the fix for the FakeIt unit tests with GCC. I guess it's because our test files are small and the includes take a lot of time to compile, maybe with a test file that is a lot bigger (and pre-compiled header ?) we could notice a difference, or maybe the overhead is so insignificant that we wouldn't notice anything anyway. Either way it looks good to me.

**Comment by malcolmdavey** [comment]
If using precompiled headers (e.g. with VS)  it might make the difference more noticeable (if fakeit.h is added to that).

**Comment by FranckRJ** [comment]
Superseded by #336. I went with a different approach that I explained in the PR.

**Pull request closed without merging**
